version: '3.8'

services:
  personal-website:
    build: .
    container_name: personal-website-container
    ports:
      - "80:8080"
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
