name: personal-website
services:
- name: web
  source_dir: /
  github:
    repo: mohamedfaridelsherbini/personal_website
    branch: main
  run_command: java -jar build/libs/personal-website-1.0-SNAPSHOT.jar
  build_command: ./gradlew build --no-daemon
  environment_slug: java
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
