name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Configure Gradle caching
        uses: gradle/gradle-build-action@v2

      - name: Lint & test
        run: ./gradlew --build-cache --parallel ktlintCheck test

      - name: Build fat JAR
        run: ./gradlew --build-cache :bootstrap:shadowJar
